# Generated by Django 4.2.6 on 2024-04-13 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('difficulty_level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContextQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('correct_answer', models.TextField()),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading.context')),
            ],
        ),
    ]
