# Generated by Django 4.2.6 on 2024-04-13 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='context',
            name='difficulty_level',
        ),
    ]
