# Generated by Django 4.2.6 on 2024-04-13 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_remove_context_difficulty_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contextquestion',
            name='correct_answer',
        ),
    ]
