# Generated by Django 4.2.6 on 2024-04-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.IntegerField(default=1),
        ),
    ]
