# Generated by Django 4.2.6 on 2024-04-14 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='topic',
            new_name='grammar_topic',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='text',
        ),
    ]
